name: SubwayFlow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: ".env,.venv,start_yee_api.sh"

      - name: Run npm install on server
        run: |
          # Create a temporary SSH key file
          echo "${{ secrets.REMOTE_SSH_KEY }}" > temp_key
          chmod 600 temp_key

          # Run npm install on the server
          ssh -i temp_key -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd ${{ secrets.REMOTE_TARGET }} && npm install && sudo systemctl restart express-app"

          # Remove the temporary SSH key file
          rm temp_key
